#!/usr/local/bin/php -q

<?php

$src  = $argv[1];
$dest = $argv[2];

//sets $xmlConfig to path of config.xml file
require_once(realpath(dirname(__FILE__) . "/../config_loc.inc.php"));
	
if (!is_readable($xmlConfig)) { trigger_error("Could not read configure xml file path=$xmlConfig", E_USER_ERROR); }
	
$configure = simplexml_load_file($xmlConfig);

$documentDirectory	= (string)$configure->documentDirectory;

copy($src, $documentDirectory.$dest);

?>

