<div class="formRow">
	<label for="ils_record">ILS Record:</label>
	<span class="static">
		<?= $this->formCheckbox("ils[create_record]", null, array("checked" => "checked", "onClick" => "Element.toggle('ils_reserve_section')")) ?>
		Create EUCLID Reserve Record
	</span>
</div>
<div id="ils_reserve_section" style="display:block;">
	<div class="formRow">
		<label for="loan_period">Loan Period:</label>
		<span class="static">		
			<select name="ils[circRule]">
				<option value="14D1R30C-5|14D1R30C-5">14D1R30C-5 -- 14D1R30C-5</option>
				<option value="1D0R1-45|1D0R1-45" selected>1D0R1-45 -- 1D0R1-45</option>
				<option value="1D0R10C-5|1D0R10C-5">1D0R10C-5 -- 1D0R10C-5</option>
				<option value="1HR2R30C-5|1HR2R30C-5">1HR2R30C-5 -- 1HR2R30C-5</option>

				<option value="2HR1R1-45|ALTRESERVE">2HR1R1-45 -- ALTRESERVE</option>
				<option value="2HR1R1-45|2HR1R1-45">2HR1R1-45 -- 2HR1R1-45</option>
				<option value="2HR2R30C-5|ALTRESERVE">2HR2R30C-5 -- ALTRESERVE</option>
				<option value="2HR2R30C-5|2HR2R30C-5">2HR2R30C-5 -- 2HR2R30C-5</option>
				<option value="3D0R1-45|3D0R1-45">3D0R1-45 -- 3D0R1-45</option>
				<option value="3D1R30C-5|3D0R1-45">3D1R30C-5 -- 3D0R1-45</option>

				<option value="3HR0R1-45|3HR0R1-45">3HR0R1-45 -- 3HR0R1-45</option>
				<option value="7D1R30C-5|7D1R30C-5">7D1R30C-5 -- 7D1R30C-5</option>
				<option value="L-2H-2-0|L-2H-2-0">L-2H-2-0 -- L-2H-2-0</option>
				<option value="NONCIRC-Y|NONCIRC-Y">NONCIRC-Y -- NONCIRC-Y</option>
				<option value="OVN0R30C-5|OVN0R30C-5">OVN0R30C-5 -- OVN0R30C-5</option>
			</select>
		</span>
	</div>
	
	<span class="helperText">
		Below is a list of copies available through EUCLID.  
		<u>Select copies for which you wish to create a EUCLID 'on-reserve' record.</u>  
		Your selection(s) will have no impact on the ReservesDirect reserves list.
	</span>
			
	<div class="formRow">
		<label for="copy">Select Copy:</label>
		<span class="static">		
			<? foreach ($this->holdings as $h) { ?>
				<? $holding_data = base64_encode(serialize($h)); ?>
				<?= $this->formCheckbox("ils[copy]", null, null, $holding_data) ?>
				<?= $h['type'] ?> | <?= $h['loc'] ?> | <?= $h['callNum'] ?> | <?= $h['bar'] ?>
				<br/>
			<? } ?>
		</span>
	</div>
</div>